gitops:
  manifest_projects:
  - id: ska-telescope/ska-cicd-gitlab-k8s-agents-config
    paths:
    - glob: '/manifests/low-itf/*.yaml'
ci_access:
  projects:
  - id: ska-telescope/ska-ser-test-equipment
