gitops:
  manifest_projects:
  - id: ska-telescope/ska-cicd-gitlab-k8s-agents-config
    paths:
    - glob: '/manifests/psi-low/*.yaml'
ci_access:
  projects:
  - id: ska-telescope/sdi/ska-cicd-stencil
      access_as:
      ci_job: {}
  - id: ska-telescope/ska-low-cbf
      access_as:
      ci_job: {}