gitops:
  manifest_projects:
  - id: ska-telescope/ska-cicd-gitlab-k8s-agents-config
    paths:
    - glob: '/manifests/psi-low/*.yaml'
ci_access:
  projects:
  - id: ska-telescope/sdi/ska-cicd-stencil
  - id: ska-telescope/ska-skampi
  - id: ska-telescope/ska-pst-recv
  - id: ska-telescope/ska-pst-lmc
  groups:
  - id: ska-telescope/low-cbf
