gitops:
  manifest_projects:
  - id: ska-telescope/ska-cicd-gitlab-k8s-agents-config
    paths:
    - glob: '/manifests/stfc-techops/*.yaml'
    - glob: '/manifests/stfc-techops/ci-dev/*.yaml'
ci_access:
  projects:
  - id: ska-telescope/sdi/ska-cicd-stencil
  - id: ska-telescope/ska-tango-examples