gitops:
  manifest_projects:
    - id: ska-telescope/ska-cicd-gitlab-k8s-agents-config
      paths:
        - glob: "/manifests/engage/*.yaml"
observability:
  logging:
    level: debug
ci_access:
  projects:
    - id: ska-telescope/sdi/ska-cicd-stencil
    - id: ska-telescope/ska-tango-examples
      access_as:
        impersonate:
          username: "system:serviceaccount:ska-tango-examples:ska-tango-examples"
